name: Update CDN

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      KEY_TORRENTS:
        required: true
      USER_TORRENTS:
        required: true
      HOST_TORRENTS:
        required: true
      KNOWN_HOSTS_TORRENTS:
        required: true

jobs:

  torrents:

    name: Update
    runs-on: [self-hosted, Linux, local]
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:

      - name: Remove previous artefacts if any
        run: |
          sudo rm -rf changes 2>/dev/null || true

      - name: Download changes
        uses: actions/download-artifact@v2
        with:
          name: changes

      - name: Check
        run: |
          [ -s changes ] || echo "SKIP=yes" >> $GITHUB_ENV

      - name: Install SSH key for torrent
        if: ${{ env.SKIP != 'yes' }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY_TORRENTS }}
          name: id_torrent # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          if_key_exists: replace

      - name: Create torrents
        if: ${{ env.SKIP != 'yes' }}
        run: ssh -T -i ~/.ssh/id_torrent ${{ secrets.USER_TORRENTS }}@${{ secrets.HOST_TORRENTS }}
